// Copyright 2026 Adobe. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, either express or
// implied. See the License for the specific language governing permissions
// and limitations under the License.
//
// Minimal real consumer of the Spectrum iOS platform-manifest cascade POC:
// reads the resolved tokens generated by ../generate.sh (which runs the
// design-data CLI against .design-data.toml's github-source pin + top-level
// manifest.json cascade) and renders each as a truecolor swatch, so the
// override/extension/foundation values are visibly, not just textually,
// distinct. See ../README.md and ../FINDINGS.md for the full cascade
// writeup — this is the "reaches a rendered pixel" half of the proof.

import Foundation

struct ResolvedToken: Decodable {
    let name: String
    let value: String
    let provenance: String
}

struct ResolvedTokens: Decodable {
    let sourceTag: String
    let tokens: [ResolvedToken]
}

struct RGB {
    let r: Int
    let g: Int
    let b: Int
}

// ponytail: parses the CLI's `rgb(...)`/`rgba(...)` string form directly —
// no CSS-color library. Extend if the demo set grows beyond rgb/rgba values.
func parseRGB(_ value: String) -> RGB? {
    guard let open = value.firstIndex(of: "("), let close = value.firstIndex(of: ")") else {
        return nil
    }
    let inner = value[value.index(after: open)..<close]
    let parts = inner.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
    guard parts.count >= 3,
          let r = Int(parts[0]), let g = Int(parts[1]), let b = Int(parts[2]) else {
        return nil
    }
    return RGB(r: r, g: g, b: b)
}

func swatch(_ rgb: RGB) -> String {
    "\u{1b}[48;2;\(rgb.r);\(rgb.g);\(rgb.b)m  \u{1b}[0m"
}

func hex(_ rgb: RGB) -> String {
    String(format: "#%02X%02X%02X", rgb.r, rgb.g, rgb.b)
}

let jsonURL = URL(fileURLWithPath: "resolved-tokens.json")
guard let data = try? Data(contentsOf: jsonURL) else {
    FileHandle.standardError.write(
        "error: couldn't read \(jsonURL.path) — run generate.sh first, and run `swift run` from consumer/.\n"
            .data(using: .utf8)!
    )
    exit(1)
}

let resolved = try! JSONDecoder().decode(ResolvedTokens.self, from: data)

print("Spectrum iOS manifest cascade — resolved tokens\n")
let nameWidth = resolved.tokens.map(\.name.count).max() ?? 0
for token in resolved.tokens {
    guard let rgb = parseRGB(token.value) else {
        print("  \(token.name): couldn't parse value \(token.value)")
        continue
    }
    let paddedName = token.name.padding(toLength: nameWidth, withPad: " ", startingAt: 0)
    print("  \(paddedName)  \(swatch(rgb))  \(hex(rgb))  (\(token.provenance))")
}

print("\n→ resolved from manifest.json cascaded over the github source (\(resolved.sourceTag))")
